stages:
  - build_nmf
  - build_nmf_opssat
  - deploy
  - deploy_extras

image: maven:3.3.9-jdk-8

variables:
  NMF_HOME: /builds/nanosat-mo-framework/nmf-ops-sat
  MAVEN_OPTS: "-Dmaven.repo.local=$NMF_HOME/.m2/repository"

build_base:
  stage: build_nmf
  script:
    - git clone https://github.com/esa/CCSDS_MO_TRANS.git
    - cd CCSDS_MO_TRANS
    - git checkout tcp_bind_fix
    - mvn clean install -PESA
    - cd ..
    - git clone https://github.com/esa/nanosat-mo-framework.git
    - cd nanosat-mo-framework
    - git checkout $NMF_BRANCH
    - mvn clean install
    - cd ..
  artifacts:
    paths:
      - $NMF_HOME/.m2/repository
      - $NMF_HOME/nanosat-mo-framework/mission/simulator/opssat-spacecraft-simulator/platformsim.properties
    expire_in: 1 day

build_ground:
  stage: build_nmf_opssat
  script:
    - cp $NMF_HOME/nanosat-mo-framework/mission/simulator/opssat-spacecraft-simulator/platformsim.properties $NMF_HOME/opssat-package/src/main/resources/space-supervisor-sim-root/
    - mvn clean install -Pground
  artifacts:
    paths:
      - $NMF_HOME/.m2/repository
      - $NMF_HOME/opssat-package/target/
    expire_in: 1 day

build_space:
  stage: build_nmf_opssat
  script:
    - mvn clean install -Pexp
  artifacts:
    paths:
      - $NMF_HOME/.m2/repository
      - $NMF_HOME/opssat-package/target/
    expire_in: 1 day

deploy_target1:
  stage: deploy
  only:
    variables:
      - $DEPLOY == "1"
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/nmf-opssat-*
    - scp -r home/ $T1USER@$TARGET1:~/nmf-opssat
    - ssh $T1USER@$TARGET1 "rm -rf /home/nmf/ /home/payloads-test/ && cp -r ~/nmf-opssat/* /home/"
    - ssh $T1USER@$TARGET1 "rm -rf ~/nmf-opssat"
  needs: ["build_ground"]

deploy_target2:
  stage: deploy
  only:
    variables:
      - $DEPLOY == "1"
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/nmf-opssat-*
    - ssh $T2USER@$TARGET2 "rm -rf nmf/"
    - scp -r home/nmf/ $T2USER@$TARGET2:~/nmf/
  needs: ["build_ground"]

deploy_target3:
  stage: deploy
  only:
    variables:
      - $DEPLOY == "1"
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/
    - scp -o ProxyCommand="ssh -W %h:%p $JUSER@$JHOST" nmf-ops-sat_*.ipk $T3USER@$TARGET3:~/
    - ssh -o ProxyCommand="ssh -W %h:%p $JUSER@$JHOST" $T3USER@$TARGET3 "opkg --force-reinstall install nmf-ops-sat_*.ipk"
    - ssh -o ProxyCommand="ssh -W %h:%p $JUSER@$JHOST" $T3USER@$TARGET3 "rm nmf-ops-sat_*.ipk"
  needs: ["build_space"]

deploy_target4:
  stage: deploy
  only:
    variables:
      - $DEPLOY == "1"
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/nmf-opssat*/experimenter-package/home/exp000
    - scp -r * $T4USER@$TARGET4:$T4PATH/$NMF_USER
    - ssh $T4USER@$TARGET4 "chown $T4USER:$T4GROUP $T4PATH/$NMF_USER && chmod 644 $T4PATH/$NMF_USER/* && find $T4PATH/$NMF_USER -type d -exec chmod a+x {} \;"
  needs: ["build_space"]

deploy_sim:
  stage: deploy_extras
  only:
    variables:
      - $DEPLOY == "1"
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/nmf-opssat-*/home/nmf/
    - scp -r -o ProxyCommand="ssh -W %h:%p $JUSER@$JHOST" lib/ supervisor-sim/ $T3USER@$TARGET3:/home/nmf/
  needs: ["deploy_target3","build_ground"]
